version: '3'
services:

  postgres:
    image: postgres:${PG_VERSION}
    container_name: ${PG_CONTAINER_NAME}
    hostname: postgres
    environment:
      - POSTGRES_USER=${PG_SUPER_USER}
      - POSTGRES_PASSWORD=${PG_SUPER_PWD}      
      - TZ=PRC
      - PGTZ=PRC
    volumes:
      - ../structure.sql:/docker-entrypoint-initdb.d/001.sql
      - ../docker/container-data/postgresql:/var/lib/postgresql/data      
    ports:
      - ${PG_LOCAL_PORT}:5432
    networks:
      - ohurlshortener

  redis:
    image: redis:${RD_VERSION}
    container_name: ${RD_CONTAINER_NAME}
    hostname: redis
    ports:    
      - ${RD_LOCAL_PORT}:6379
    networks:
      - ohurlshortener 
      
networks:
  ohurlshortener:
    driver: bridge
    name: "network_ohurlshortener"
    driver_opts:
      com.docker.network.enable_ipv6: "true"